# Generated by Django 3.1.12 on 2022-07-21 09:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import version_management_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateSent',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('versions', djongo.models.fields.ArrayField(model_container=version_management_app.models.VersionAbstract)),
                ('noof_versions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dd', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('vv', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ep', models.CharField(max_length=128)),
                ('sent_date', models.DateField()),
                ('dt', djongo.models.fields.EmbeddedField(model_container=version_management_app.models.SensorValues)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='version_management_app.device')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='version_management_app.version')),
            ],
            options={
                'ordering': ['sent_date'],
            },
        ),
    ]
